- name: Deploy and install veepeenet on remote hosts
  hosts: all
  tasks:
    - name: Create temporary directory on remote host
      ansible.builtin.tempfile:
        state: directory
        suffix: veepeenet
      register: remote_temp_dir
      check_mode: false

    - name: Download VeePeeNET deb package
      ansible.builtin.get_url:
        url: "https://github.com/spector517/veepeenet/releases/download/{{ release_version }}/veepeenet_{{ release_version }}_amd64.deb"
        dest: "{{ remote_temp_dir.path }}/veepeenet_{{ release_version }}_amd64.deb"
        mode: '0644'
      check_mode: false

    - name: Install VeePeeNET deb package
      ansible.builtin.apt:
        deb: "{{ remote_temp_dir.path }}/veepeenet_{{ release_version }}_amd64.deb"
      become: true

    - name: Clean up temporary files
      ansible.builtin.file:
        path: "{{ remote_temp_dir.path }}"
        state: absent
      check_mode: false
