# Deploy this file to /etc/zabbix/zabbix_agent2.d/veepeenet.conf
# Deploy veepeenet_status.sh to /etc/zabbix/scripts/veepeenet_status.sh and make it executable.
UserParameter=veepeenet.status.raw,/etc/zabbix/scripts/veepeenet_status.sh